### ISSUE TITLE
Performance X Size Compress

### ISSUE THREAD

**Issue by rafaelpivetta** [flanglet/kanzi#1]
I have tested the kanzi package with a image and the performance is fast, you really has done a great job.
But the gz format is more compressed and fastest than that snp, 18 kb aproximately. It's possible reduce the size of the snp format? Or this is not the objective of the snp format?
In my test the size buffer in .gz is the same that used in snp format 32768.

GZIPOutputStream out = new GZIPOutputStream(new FileOutputStream(outfile));
        byte[] buf = new byte[32768];
        int len;
        while ((len = in.read(buf)) > 0) {
            out.write(buf, 0, len);
        }

I replaced the CompressedOutputStream("None", "Snappy", out); by CompressedOutputStream(out) of the emory-util-io.jar version 2.1 and the snappy more fastest than .gz, but still the snp is bigger, aproximately 7 kb.

\<dependency>
	\<groupId>edu.emory.mathcs.util\</groupId>
	\<artifactId>emory-util-io\</artifactId>
	\<version>2.1\</version>
\</dependency>'

**Comment by flanglet** [comment]
Hi Rafael,

I am not sure what you are trying to do and what you call 'kanzi format'.
The block compressor allows many different options for transform and
entropy. Depending on the option you choose, you decide whether you want
fast compression (but low compression ratio ... like LZ4) or slow
compression (but high compression ratio, say BWT+CM). Block size also
matters. Which option combination are you using ? BWT+CM or BWT+PAQ is
going to beat GZ hands down in compression ratio. So, it really depends on
your compression command line options.

Frederic

**Comment by rafaelpivetta** [comment]
Frederic,
Two objectives:
1 - resize a large image to 640x480 ( pixels ) if possible without losing quality , the image should have a maximum of 35 Kb . I'm not sure if kanzi.jar is used for this.
2 - Compress the previous image using BlockCompressor line command or the method compressKanzi(String arg) of the class TestSnappy.java (BWT + CM).
I would like the file size was smaller than using GZIPOutputStream.

Rafael

**Comment by flanglet** [comment]
Rafael,

A few comments.
First, using a generic data compressor will not work as well as an image compressor. You may just want to try Java's JPEG encoder:
JPEGImageWriter imageWriter = (JPEGImageWriter) ImageIO.getImageWritersBySuffix("jpeg").next();
    ImageOutputStream ios = ImageIO.createImageOutputStream(fos);
    imageWriter.setOutput(ios);
Second, if you want to use Kanzi's block compressor, do not use TestSnappy.java. Snappy is geared towards speed but has a weak compression ratio and the class TestSnappy is not part of the project but used to compared implementation speeds. To get a better compression ratio with the block compressor,
from the command line: java -cp kanzi.jar kanzi.app.BlockCompressor -input=XXX -output=XXX.knz -overwrite -block=1m -transform=bwt -entropy=cm
from code: you can instantiate BlockCompressor or CompressedOutputStream. See BlockCompressor.java.
EG: new CompressedOutputStream("CM", "BWT", fileouputstream, 1024*1024, true, null, 1); 
Obviously the block compressor is lossless, so in order to achieve a goal of 35 kb, you may have to drop some data during phase 1 (resize). Take a look at kanzi,util.sampling (and the use in kanzi.test.TestColorModel). You could down sample the image by 2 (x4 smaller) then block compress with a miminal quality loss.

**Comment by rafaelpivetta** [comment]
Frederic,
Ok. 
With the "-options" -transform=bwt -entropy=cm or -transform=bwt -entropy=paq, the image file (jpeg) compressed (.knz) is smaller than .gz.


In the TestColorModel test, the error below occurs. My image is 640x480 and the source code kanzi-master.zip.

640x480
================ Test round trip RGB -> YXX -> RGB ================
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at kanzi.util.color.XYZColorModelConverter.convertYUVtoRGB(XYZColorModelConverter.java:200)
	at kanzi.test.TestColorModel.test(TestColorModel.java:155)
	at kanzi.test.TestColorModel.main(TestColorModel.java:120)

**Comment by flanglet** [comment]
I fixed the ArrayIndexOutOfBoundsException in the latest push.
